[project]
name = "customer-support-eval"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "logfire>=4.40.0",
    "pydantic-ai-slim[google,openai]>=2.27.0",
    "pydantic-evals>=2.27.0",
    "python-dotenv>=1.2.2",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
]
